version: "3.7"
services:
  xgds:
    image: xgds-subsea:current
    hostname: xgds-subsea
    depends_on:
      - mariadb
      - couchdb
      - redis

    # ===================================
    # if you want to develop locally,
    # uncomment the four lines below, making sure to run:
    # export XGDS_WORKING_DIRECTORY=/path/to/xgds
    # ===================================
    volumes:
      - ${XGDS_HOME_DIRECTORY}:/root
      - usr-local:/usr/local
      - ${XGDS_DATA_DIRECTORY}:${XGDS_DATA_DIRECTORY}

    networks:
      - xgds-docker-net
    ports:
      - target: 13060  # HER
        published: 13060
        protocol: udp
        mode: host
      - target: 13069  # NAV
        published: 13069
        protocol: udp
        mode: host
      - target: 13065  # TEM
        published: 13065
        protocol: udp
        mode: host
      - target: 13064  # CTD
        published: 13064
        protocol: udp
        mode: host
      - target: 13067  # EVENT
        published: 13067
        protocol: udp
        mode: host
      - target: 13077  # CHAT
        published: 13077
        protocol: udp
        mode: host
      - target: 13078  # GRABHD
        published: 13078
        protocol: udp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}

  mariadb:
    image: mariadb:latest
    hostname: mariadb-subsea
    environment:
      MYSQL_ROOT_PASSWORD: xgds
      MYSQL_DATABASE: xgds_subsea
    volumes:
      - mariadb-data:/var/lib/mysql
      - /usr/local/mysql/conf:/etc/mysql
      - /usr/local/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - xgds-docker-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}

  geoserver:
    image: xgds-geoserver:current
    hostname: geoserver-subsea
    volumes:
      - /usr/local/geoserver/data_dir:/usr/share/geoserver/data_dir
    networks:
      - xgds-docker-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}

  owa:
    image: owa:current
    hostname: owa
    volumes:
      - owa-data:/var/www/html
    networks:
      - xgds-docker-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - mariadb
      
  redis:
    image: redis:5-alpine
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      - xgds-docker-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}

  couchdb:
    image: couchdb:latest
    hostname: couchdb-subsea
    volumes:
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data
        volume:
          nocopy: false
      - type: volume
        source: couchdb-config
        target: /opt/couchdb/etc
        volume:
          nocopy: false
    ports:
      - "5984:5984"
    networks:
      - xgds-docker-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      placement:
        constraints:
          - node.hostname == ${LOCAL_DOCKER_HOST}

volumes:
  couchdb-data:
    labels:
      persistent: 1
  couchdb-config:
    labels:
      persistent: 1
  redis-data:
    labels:
      persistent: 1
  geoserver-data:
    labels:
      persistent: 1
  mariadb-data:
    labels:
      persistent: 1
  usr-local:
    labels:
      persistent: 1
  owa-data:
    labels:
      persistent: 1

networks:
  xgds-docker-net:
    external: true
    
