# ================================================================================
# https://github.com/xgds/ansible-provision/blob/master/apache/apache-defaults.yml
# ================================================================================
apache_http_port: 8181
apache_https_port: 443
apache_configure_ssl: no
apache_cert_file: null
apache_key_file: null
apache_cert_chain_file: null
# ================================================================================

# ================================================================================
# https://github.com/xgds/ansible-provision/blob/master/xgds-base-setup.yml
# ================================================================================
user_source_root: null
source_root: "{{ user_source_root | default(ansible_user_dir, true) }}"
mysql_host: mysql
mysql_user: root
db_password: password
bing_maps_api_key: "{{ lookup('env', 'BING_MAPS_API_KEY') }}"
django_superuser: xgds
django_superuser_password: xgds
xgds_sitename: subsea
# ================================================================================
