- hosts: 127.0.0.1
  connection: local

  tasks:
  - include_vars:
      file: ./pip3.yml
      name: pip3
  - pip3:
      name: pip3
      state: latest
  - pip3:
      name: "{{ pip3['pip3_package_list'] }}"

