- hosts: 127.0.0.1
  connection: local
  vars_files:
    - variables.yml
  tasks:
  - lineinfile:
      name: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^character-set-server  ='
      line: 'character-set-server  = utf8'

  - lineinfile:
      name: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^collation-server      ='
      line: 'collation-server      = utf8_general_ci'

  - lineinfile:
      name: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address            = 127.0.0.1'
      line:    'bind-address            = 0.0.0.0'

  - name: Start manually if running in Docker build
    shell: /usr/bin/mysqld_safe </dev/null >/dev/null 2>&1 &

  - name: Wait for MySQL startup
    wait_for:
      path: /var/run/mysqld/mysqld.sock
      delay: 5
      timeout: 60

  - name: Clear plugin setting for MySQL root user
    shell: "mysql -u root -e \"update mysql.user set plugin='' where host='localhost'\""
    
  - name: Ensure Anonymous user(s) are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost
      - "{{ ansible_hostname }}"

  - name: Remove the test database
    mysql_db: name=test state=absent
    
  - name: Update MySQL root password for all root accounts
    mysql_user:
      name: "root"
      host: "%"
      password: "{{ db_password | default('') }}"
      state: present
      priv: '*.*:ALL,GRANT'

  - name: Create empty xGDS database
    mysql_db:
      name: xgds_{{ xgds_sitename }}
      state: present
      login_user: "{{ mysql_user }}"
      login_password: "{{ db_password }}"
    register: xgds_database
    when: base_only is not defined

  - name: Repair databases
    shell: "mysqlcheck -uroot -p{{db_password}}  --repair --all-databases"
