- hosts: 127.0.0.1
  connection: local

  tasks:
  - include_vars:
      file: ./npm.yml
      name: npm
  - shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt:
      name: nodejs
      update_cache: yes
  - npm:
      name:  "{{ item.name }}"
      state: "{{ item.state }}"
      global: yes
    with_items:
      - "{{ npm['npm_package_list'] }}"

